// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const FoodPellet = __t.object("FoodPellet", {
  id: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  radius: __t.f32(),
});
export type FoodPellet = __Infer<typeof FoodPellet>;

export const GameConfig = __t.object("GameConfig", {
  id: __t.u32(),
  maxFood: __t.u32(),
  worldWidth: __t.u32(),
  worldHeight: __t.u32(),
});
export type GameConfig = __Infer<typeof GameConfig>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  radius: __t.f32(),
  mass: __t.f32(),
  color: __t.u32(),
});
export type Player = __Infer<typeof Player>;

