// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const EjectedMass = __t.object("EjectedMass", {
  id: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  radius: __t.f32(),
  mass: __t.f32(),
});
export type EjectedMass = __Infer<typeof EjectedMass>;

export const FoodPellet = __t.object("FoodPellet", {
  id: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  radius: __t.f32(),
});
export type FoodPellet = __Infer<typeof FoodPellet>;

export const GameConfig = __t.object("GameConfig", {
  id: __t.u32(),
  maxFood: __t.u32(),
  worldWidth: __t.u32(),
  worldHeight: __t.u32(),
});
export type GameConfig = __Infer<typeof GameConfig>;

export const MassDecaySchedule = __t.object("MassDecaySchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MassDecaySchedule = __Infer<typeof MassDecaySchedule>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  radius: __t.f32(),
  mass: __t.f32(),
  color: __t.u32(),
});
export type Player = __Infer<typeof Player>;

export const PlayerCell = __t.object("PlayerCell", {
  cellId: __t.u64(),
  playerIdentity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  radius: __t.f32(),
  mass: __t.f32(),
});
export type PlayerCell = __Infer<typeof PlayerCell>;

export const SplitMergeSchedule = __t.object("SplitMergeSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  playerIdentity: __t.identity(),
});
export type SplitMergeSchedule = __Infer<typeof SplitMergeSchedule>;

