// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import DespawnPlayerReducer from "../despawn_player_reducer";
import EatFoodReducer from "../eat_food_reducer";
import SpawnPlayerReducer from "../spawn_player_reducer";
import UpdatePositionReducer from "../update_position_reducer";

export type DespawnPlayerParams = __Infer<typeof DespawnPlayerReducer>;
export type EatFoodParams = __Infer<typeof EatFoodReducer>;
export type SpawnPlayerParams = __Infer<typeof SpawnPlayerReducer>;
export type UpdatePositionParams = __Infer<typeof UpdatePositionReducer>;

